[package]
edition = { workspace = true }
license = { workspace = true }
name = "lean-dup-report"
version = { workspace = true }

[dependencies]
lean-dup-diagnostics = { workspace = true }
lean-dup-eval = { workspace = true }
lean-dup-index = { workspace = true }
lean-dup-search = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lib]
doctest = false
