[package]
edition = { workspace = true }
license = { workspace = true }
name = "lean-dup-search"
version = { workspace = true }

[dependencies]
lean-dup-diagnostics = { workspace = true }
lean-dup-index = { workspace = true }
lean-dup-project = { workspace = true }
lean-dup-worker = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false
