[package]
edition = { workspace = true }
license = { workspace = true }
name = "lean-dup-cli"
version = { workspace = true }

[[bin]]
name = "lean-dup"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
lean-dup-diagnostics = { workspace = true }
lean-dup-eval = { workspace = true }
lean-dup-index = { workspace = true }
lean-dup-project = { workspace = true }
lean-dup-report = { workspace = true }
lean-dup-search = { workspace = true }
lean-dup-worker = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
rusqlite = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }

[lib]
doctest = false
