[package]
build = "build.rs"
edition = { workspace = true }
license = { workspace = true }
name = "lean-dup-worker-child"
version = { workspace = true }

[dependencies]
lean-rs-worker-child = { workspace = true }

[build-dependencies]
lean-toolchain = { workspace = true }

[[bin]]
name = "lean-dup-worker-child"
path = "src/main.rs"

[lints]
workspace = true
