[package]
publish = false
edition = { workspace = true }
license = { workspace = true }
name = "lean-dup-vector-search"
version = { workspace = true }

[dependencies]
clap = { workspace = true }
lean-dup-diagnostics = { workspace = true }
lean-dup-embedding = { workspace = true }
lean-dup-eval = { workspace = true }
lean-dup-index = { workspace = true }
lean-dup-project = { workspace = true }
lean-dup-search = { workspace = true }
lean-dup-vector-index = { workspace = true }
lean-dup-worker = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false
