"""Declaration features used for duplicate triage."""

from __future__ import annotations

import re
from dataclasses import dataclass

from lean_dup.matching import LOW_SIGNAL_NAME_TOKENS, jaccard, name_tokens
from lean_dup.models import Declaration

LOW_SIGNAL_HEADS = frozenset(
    {
        "Eq",
        "Iff",
        "Exists",
        "False",
        "True",
        "Nonempty",
        "LE.le",
        "LT.lt",
        "Ne",
        "Membership.mem",
        "HasSubset.Subset",
        "And",
        "Or",
        "Not",
    }
)
GENERATED_SHORT_NAMES = frozenset(
    {
        "rec",
        "recOn",
        "casesOn",
        "noConfusion",
        "noConfusionType",
        "below",
        "brecOn",
        "ibelow",
        "binductionOn",
        "ctorElim",
        "elim",
    }
)


@dataclass(frozen=True)
class PairFeatures:
    """Cheap pairwise evidence before expensive probes."""

    constants: float
    names: float
    same_heads: bool
    shared_heads: tuple[str, ...]
    same_namespace: bool
    same_namespace_family: bool
    same_conclusion: bool
    same_source_skeleton: bool
    exact_statement: bool
    same_permutation: bool
    same_connective: bool


def is_generated(declaration: Declaration) -> bool:
    """Return whether a declaration is likely generated by Lean or notation elaboration."""

    short = declaration.short_name
    if short in GENERATED_SHORT_NAMES:
        return True
    if short.startswith("_aux_") or "._aux_" in declaration.name:
        return True
    if "._unexpand_" in declaration.name or "._macroRules_" in declaration.name:
        return True
    if re.search(r"(^|[.])term[^.]*_$", declaration.name):
        return True
    return False


def is_backport(declaration: Declaration) -> bool:
    """Return whether a declaration is in a local mathlib backport namespace."""

    return ".Mathlib4Backports." in declaration.module or declaration.module.endswith(
        "Mathlib4Backports"
    )


def namespace_family(name: str, *, depth: int = 3) -> str:
    """Return a suffix namespace family suitable for proximity scoring."""

    namespace = name.rsplit(".", 1)[0]
    parts = [part for part in namespace.split(".") if part]
    return ".".join(parts[-depth:])


def useful_name_tokens(declaration: Declaration) -> set[str]:
    """Return declaration name tokens minus low-signal connective words."""

    return name_tokens(declaration.short_name) - LOW_SIGNAL_NAME_TOKENS


def useful_heads(declaration: Declaration) -> set[str]:
    """Return statement heads that are useful as domain evidence."""

    return set(declaration.type_heads) - LOW_SIGNAL_HEADS


def broad_conclusion(declaration: Declaration) -> bool:
    """Return whether the declaration conclusion is too broad to drive confidence alone."""

    heads = set(declaration.type_heads)
    if not heads:
        return False
    return bool(heads) and heads <= LOW_SIGNAL_HEADS


def pair_features(first: Declaration, second: Declaration) -> PairFeatures:
    """Compute cheap pairwise features."""

    first_namespace = first.name.rsplit(".", 1)[0]
    second_namespace = second.name.rsplit(".", 1)[0]
    shared_heads = tuple(sorted(useful_heads(first) & useful_heads(second)))
    return PairFeatures(
        constants=jaccard(set(first.constants), set(second.constants)),
        names=jaccard(useful_name_tokens(first), useful_name_tokens(second)),
        same_heads=bool(first.type_heads) and set(first.type_heads) == set(second.type_heads),
        shared_heads=shared_heads,
        same_namespace=first_namespace == second_namespace,
        same_namespace_family=namespace_family(first.name) == namespace_family(second.name),
        same_conclusion=first.conclusion_fingerprint == second.conclusion_fingerprint,
        same_source_skeleton=bool(
            first.source_fingerprint and first.source_fingerprint == second.source_fingerprint
        ),
        exact_statement=first.type_fingerprint == second.type_fingerprint,
        same_permutation=first.permutation_fingerprint == second.permutation_fingerprint,
        same_connective=first.connective_fingerprint == second.connective_fingerprint,
    )


def pair_signal_score(first: Declaration, second: Declaration) -> tuple[float, tuple[str, ...]]:
    """Score one pair for near-candidate ordering and explain the score."""

    features = pair_features(first, second)
    evidence: list[str] = []
    if features.constants > 0:
        evidence.append(f"shared-constants={features.constants:.2f}")
    if features.shared_heads:
        evidence.append("shared-useful-heads=" + ",".join(features.shared_heads[:4]))
    elif features.same_heads:
        evidence.append("same-low-signal-heads")
    if features.names > 0:
        evidence.append(f"name-tokens={features.names:.2f}")
    if features.same_conclusion:
        evidence.append("same-conclusion")
    if features.same_permutation:
        evidence.append("same-permutation-fingerprint")
    if features.same_connective:
        evidence.append("same-connective-fingerprint")
    if features.same_namespace_family:
        evidence.append("same-namespace-family")
    if features.same_source_skeleton:
        evidence.append("same-source-skeleton")
    score = (
        features.constants * 0.34
        + min(len(features.shared_heads), 3) * 0.08
        + features.names * 0.10
        + (0.14 if features.same_conclusion else 0.0)
        + (0.16 if features.same_permutation else 0.0)
        + (0.08 if features.same_connective else 0.0)
        + (0.06 if features.same_namespace_family else 0.0)
        + (0.12 if features.same_source_skeleton else 0.0)
    )
    if not features.shared_heads and features.constants == 0 and features.names == 0:
        score *= 0.45
    return min(score, 1.0), tuple(evidence)
